import re
from pathlib import Path

# Resolve paths relative to this script's location so the script works
# correctly regardless of which directory it is run from.
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

# Directories under server/reference/ that should never be included in the
# help tables output (not user-facing SQL reference content).
EXCLUDED_DIRS = [
    "system-tables",
    "error-codes",
    "clientserver-protocol",
    "product-development",
]

# Maps a directory path segment to its help_category_id in mysql.help_category.
# The first matching key wins, so more specific entries should come first.
# If no key matches, the topic is assigned category 35 (Contents) by default.
CATEGORY_MAP = {
    "string-functions": 37,
    "aggregate-functions": 16,
    "numeric-functions": 4,
    "date-time-functions": 31,
    "control-flow-functions": 7,
    "encryption-functions": 12,
    "information-functions": 17,
    "bit-functions": 19,
    "miscellaneous-functions": 14,
    "data-types": 22,
    "plugins": 5,
    "stored-procedures": 33,
    "stored-functions": 33,
    "stored-routines": 33,
    "transactions": 8,
    "data-definition": 39,
    "data-manipulation": 27,
    "account-management": 10,
    "geometry": 34,
    "geometry-constructors": 24,
    "geometry-properties": 36,
    "geometry-relations": 30,
    "sql-language-structure": 29,
    "operators": 38,
    "comparison-operators": 18,
    "logical-operators": 15,
    "user-defined-functions": 21,
    "table-maintenance": 20,
    "administrative": 26,
}

# The static set of help_category rows that must exist before any help_topic
# rows are inserted (topics reference categories by ID). These mirror the
# categories in the original MariaDB fill_help_tables.sql exactly.
HELP_CATEGORIES = [
    (1, 'Geographic', 0, ''),
    (2, 'Polygon properties', 34, ''),
    (3, 'WKT', 34, ''),
    (4, 'Numeric Functions', 38, ''),
    (5, 'Plugins', 35, ''),
    (6, 'MBR', 34, ''),
    (7, 'Control flow functions', 38, ''),
    (8, 'Transactions', 35, ''),
    (9, 'Help Metadata', 35, ''),
    (10, 'Account Management', 35, ''),
    (11, 'Point properties', 34, ''),
    (12, 'Encryption Functions', 38, ''),
    (13, 'LineString properties', 34, ''),
    (14, 'Miscellaneous Functions', 38, ''),
    (15, 'Logical operators', 38, ''),
    (16, 'Functions and Modifiers for Use with GROUP BY', 35, ''),
    (17, 'Information Functions', 38, ''),
    (18, 'Comparison operators', 38, ''),
    (19, 'Bit Functions', 38, ''),
    (20, 'Table Maintenance', 35, ''),
    (21, 'User-Defined Functions', 35, ''),
    (22, 'Data Types', 35, ''),
    (23, 'Compound Statements', 35, ''),
    (24, 'Geometry constructors', 34, ''),
    (25, 'GeometryCollection properties', 1, ''),
    (26, 'Administration', 35, ''),
    (27, 'Data Manipulation', 35, ''),
    (28, 'Utility', 35, ''),
    (29, 'Language Structure', 35, ''),
    (30, 'Geometry relations', 34, ''),
    (31, 'Date and Time Functions', 38, ''),
    (32, 'WKB', 34, ''),
    (33, 'Procedures', 35, ''),
    (34, 'Geographic Features', 35, ''),
    (35, 'Contents', 0, ''),
    (36, 'Geometry properties', 34, ''),
    (37, 'String Functions', 38, ''),
    (38, 'Functions', 35, ''),
    (39, 'Data Definition', 35, ''),
]

SQL_PREAMBLE = """\
-- Copyright (c) 2003, 2008-2012, Oracle and/or its affiliates. All rights reserved.
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; version 2 of the License.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

-- DO NOT EDIT THIS FILE. It is generated automatically.

-- To use this file, load its contents into the mysql database. For example,
-- with the mysql client program, process the file like this, where
-- file_name is the name of this file:

--     mysql -u root -p mysql < file_name

set names 'utf8';

set sql_log_bin = 0;

use mysql;
delete from help_topic;
delete from help_category;
delete from help_keyword;
delete from help_relation;
"""

def get_category_id(path: str) -> int:
    """Match directory path to category ID. Returns 35 (Contents) if no match."""
    # Walk CATEGORY_MAP in definition order; first matching segment wins.
    for key, cat_id in CATEGORY_MAP.items():
        if key in path:
            return cat_id
    return 35  # Default: Contents


def extract_keywords(name):
    """Extract keyword tokens from a topic name for help_keyword entries."""
    # Strip escape characters (e.g. backslashes from markdown), then split on
    # whitespace, commas, or slashes to get individual tokens.
    clean_name = name.replace('\\', '')
    words = re.split(r'[\s,/]+', clean_name)
    keywords = [w.upper() for w in words if len(w.strip()) > 0]
    return keywords


def get_files(base_path: str = "server/reference") -> list:
    """Find all .md files in base_path, excluding EXCLUDED_DIRS and empty READMEs."""
    files = []
    base = Path(base_path)
    
    for md_file in base.rglob("*.md"):
        path_str = str(md_file)
        
        # Skip directories that contain non-reference content
        if any(excluded in path_str for excluded in EXCLUDED_DIRS):
            continue
        
        # README files are navigation/index pages, not reference entries.
        # Skip ones with ≤3 lines (they're effectively empty).
        if md_file.name == "README.md":
            try:
                line_count = sum(1 for _ in open(md_file, 'r', encoding='utf-8'))
                if line_count <= 3:
                    continue
            except Exception:
                continue
            
        files.append(path_str)
    
    # Sort so processing order is deterministic (affects which duplicate wins)
    return sorted(files)


def open_file(file_path: str):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read().splitlines()

    
def find_line_range(data: list):
    """Find the useful content range in a file.

    Returns (content_lines, topic_name) where content_lines runs from the
    H1 title to the first end-marker (See Also / Marketo form / license sub).
    Returns (None, None) if no H1 title is found.
    """
    start = None
    end = None
    name = None
    data_length = len(data)
    
    # Find the first top-level heading — this becomes the help topic name.
    for line in range(data_length):
        if data[line].startswith("# "):
            start = line
            name = data[line].lstrip("# ")
            break
    
    if start is None:
        return None, None
    
    see_also_pattern = re.compile(r'^#{2,}\s*see\s+also', re.IGNORECASE)
    
    # Stop at the first end-marker so we don't include navigation boilerplate.
    for line in range(start, data_length):
        if (see_also_pattern.match(data[line]) 
            or data[line].lower().startswith("{% @marketo/form") 
            or data[line].lower().startswith("<sub>")):
            end = line
            break
    
    if end is None:
        end = data_length
    
    content = data[start:end]
    return content, name


def extract_sections(content: list):
    """Split page content into syntax, description, and example sections.

    Looks for standard GitBook heading markers:
      ## Syntax        → SQL syntax block
      ## Description   → prose description (also accepts ## Overview)
      ## Example(s)    → SQL example block

    Falls back gracefully when headings are missing.
    Returns (syntax_str, desc_str, example_lines).
    """
    syntax_start = None
    desc_start = None
    example_start = None
    
    syntax_pattern = re.compile(r'^#{2,}\s*syntax', re.IGNORECASE)
    desc_pattern = re.compile(r'^#{2,}\s*(description|overview)', re.IGNORECASE)
    example_pattern = re.compile(r'^#{2,}\s*examples?', re.IGNORECASE)
    
    for line in range(len(content)):
        if syntax_pattern.match(content[line]):
            syntax_start = line
        elif desc_pattern.match(content[line]) and desc_start is None:
            desc_start = line
        elif example_pattern.match(content[line]) and example_start is None:
            example_start = line

    # Standard case: has Syntax and Description/Overview
    if syntax_start is not None and desc_start is not None:
        syntax = content[syntax_start:desc_start]
        syntax_content = extract_code_block(syntax)
        if example_start:
            desc = content[desc_start+1:example_start]
        else:
            desc = content[desc_start+1:]
    # Has Description/Overview but no Syntax
    elif desc_start is not None:
        syntax_content = []
        if example_start:
            desc = content[desc_start+1:example_start]
        else:
            desc = content[desc_start+1:]
    # Fallback: no Syntax, no Description — treat all prose after the title as description
    else:
        syntax_content = []
        if example_start:
            desc = content[1:example_start]  # Skip title line
        else:
            desc = content[1:]  # Everything after title
    
    # Extract example code block (first ```sql block after the Examples heading)
    example_content = extract_code_block(content[example_start+1:] if example_start else [])
    
    syntax_str = "\n".join(syntax_content) if syntax_content else ""
    desc_str = "\n".join(desc)
 
    return syntax_str, desc_str, example_content


def extract_code_block(lines: list):
    """Return the lines inside the first ```sql ... ``` fenced code block.

    Returns an empty list if no such block is found.
    """
    start = None
    stop = None
    
    for i in range(len(lines)):
        if lines[i] == "```sql" and start is None:
            start = i
        elif lines[i] == "```" and start is not None:
            stop = i
            break
    
    if start is not None and stop is not None:
        return lines[start+1:stop]
    
    return []


def strip_markdown(text: str) -> str:
    """Convert markdown to plain text for clean HELP output.

    The MariaDB HELP command displays raw text, so markdown syntax like
    links, backticks, bold, and template tags must be stripped out.
    """
    # Remove GitBook/Marketo template tags: {% hint %}, {% @marketo %}, etc.
    text = re.sub(r'\{%.*?%\}', '', text)
    # Convert [link text](url) → link text
    text = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', text)
    # Remove backtick code formatting: `value` → value
    text = re.sub(r'`([^`]+)`', r'\1', text)
    # Remove escaped underscores (common in MariaDB docs for function names)
    text = text.replace('\\_', '_')
    # Remove bold and italic markers
    text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
    text = re.sub(r'\*([^*]+)\*', r'\1', text)
    # Remove heading markers (## headings become plain text in HELP output)
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    # Collapse 3+ blank lines into 2 to keep output readable
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def truncate_to_bytes(text: str, max_bytes: int = 60000) -> str:
    """Truncate a string so its UTF-8 encoding fits within max_bytes.

    MariaDB's help_topic.description column is TEXT (max 65,535 bytes).
    We use 60,000 as a conservative limit to leave headroom.
    """
    encoded = text.encode('utf8')
    if len(encoded) <= max_bytes:
        return text
    truncated = encoded[:max_bytes].decode('utf8', errors='ignore')
    return truncated.rstrip() + '\n\n[Truncated — full content at mariadb.com/docs]'

def build_output(name, syntax: str, desc: str, example: list, path: str):
    """Assemble the final description string and topic metadata.

    Combines syntax, description, and examples into a single plain-text block
    using the same section-header format as the original MariaDB help tables:

        Syntax
        ------
        ...

        Description
        -----------
        ...

        Examples
        --------
        ...

        URL: https://...

    The 'example' field in the INSERT is left empty — all content lives in
    'description', matching how the original fill_help_tables.sql is structured.
    """
    parts = []
    if syntax:
        parts.append(f"Syntax\n------\n\n{syntax}")
    if desc.strip():
        parts.append(f"Description\n-----------\n\n{desc}")
    if example:
        example_str = "\n".join(example)
        parts.append(f"Examples\n--------\n\n{example_str}")
    desc_str = "\n\n".join(parts) if parts else ""
    desc_str = strip_markdown(desc_str)
    # `path` comes from get_files() which walks REPO_ROOT/server/reference as
    # an absolute path, so each entry is an absolute filesystem path (in CI:
    # /home/runner/work/mariadb-docs/mariadb-docs/...). Make it relative to
    # REPO_ROOT before tacking it onto the docs URL — otherwise we ship URLs
    # like https://mariadb.com/docs//home/runner/... (broken) instead of
    # https://mariadb.com/docs/server/reference/... (right).
    url_path = str(Path(path).resolve().relative_to(REPO_ROOT)).removesuffix(".md")
    url = f"https://mariadb.com/docs/{url_path}"
    desc_str += f"\n\nURL: {url}"
    desc_str = truncate_to_bytes(desc_str)

    # help_topic.name is CHAR(64) — truncate if over limit
    if len(name) > 64:
        name = name[:64]

    content = {
        "name": name,
        "description": desc_str, 
        "example": "",  # Intentionally empty; all content is in description
        "url": url,
    }

    return content

def escape_sql(text):
    """Escape text for safe embedding in a SQL single-quoted string.

    Order matters: backslashes must be escaped before the other substitutions
    so we don't double-escape characters introduced by later replacements.
    """
    text = text.replace("\\", "\\\\")  # \ → \\
    text = text.replace("'", "''")      # ' → '' (SQL standard escaping)
    text = text.replace("\n", "\\n")   # newline → literal \n for single-line INSERT
    return text

def generate_insert(name, description, example, help_topic_id, url, help_category_id):

    sql = (
        f"INSERT INTO help_topic (help_topic_id, help_category_id, name, description, example, url) "
        f"VALUES ({help_topic_id}, {help_category_id}, '{name}', '{description}', '{example}', '{url}');"
    )
    return sql


def process_single_file(path: str, help_topic_id: int) -> dict:
    """Process a single Markdown file into a help_topic dict.

    Returns a dict with keys: sql, topic_id, name, description_plain.
    Returns None if the file has no title, no content, or raises an exception.
    'description_plain' holds the unescaped description text and is used by
    process_batch() to compare content quality when resolving duplicates.
    """
    try:
        data = open_file(path)
        content, name = find_line_range(data)
        
        if content is None:
            return None
            
        syntax, desc, example = extract_sections(content)
        
        # Skip files with no meaningful content (empty description and no examples)
        desc_stripped = desc.strip()
        if not desc_stripped and not example:
            return None
        
        full_content = build_output(name, syntax, desc, example, path)

        name_ = escape_sql(full_content["name"])
        description_ = escape_sql(full_content["description"])
        example_ = escape_sql(full_content["example"])
        url_ = escape_sql(full_content["url"])
        category_id = get_category_id(path)
        
        sql = generate_insert(name_, description_, example_, help_topic_id, url_, category_id)
        return {
            'sql': sql,
            'topic_id': help_topic_id,
            'name': full_content['name'],
            'description_plain': full_content['description'],  # unescaped, for dedup scoring
        }
        
    except Exception as e:
        print(f"Failed to parse {path}: {e}")
        return None


# Phrases that identify a page as a plugin stub rather than a reference page.
# Pages whose description starts with one of these are treated as low-quality
# and will lose when competing with another page for the same topic name.
_STUB_PHRASES = [
    "this plugin implements",
    "this plugin provides",
    "this is a synonym for",
    "a synonym for",
]


def _is_stub(description: str) -> bool:
    """Return True if the description looks like a plugin stub or synonym page."""
    first_line = description.strip().lower().splitlines()[0] if description.strip() else ""
    return any(first_line.startswith(phrase) for phrase in _STUB_PHRASES)


def process_batch(file_list: list, start_id: int = 0) -> list:
    """Process all files and return (topics, failed) lists.

    Deduplication strategy:
    - Topic names are case-insensitive (MariaDB CHAR columns are CI by default).
    - When two files produce the same name, the one with more meaningful content
      wins. Plugin stub pages (description starts with 'This plugin implements'
      etc.) are always treated as lower-quality and discarded in favour of the
      actual reference page.
    - If neither or both are stubs, the one seen first (alphabetically earlier
      path) wins — consistent with sorted file discovery order.
    """
    # First pass: collect all results keyed by lower-case topic name.
    # We store (result, path) so we can compare and replace.
    best: dict[str, tuple[dict, str]] = {}
    failed = []

    for path in file_list:
        # Use a placeholder ID of 0 for now; IDs are assigned in the second pass.
        result = process_single_file(path, 0)
        if result is None:
            failed.append(path)
            continue

        name_lower = result['name'].lower()

        if name_lower not in best:
            best[name_lower] = (result, path)
        else:
            existing_result, existing_path = best[name_lower]
            existing_is_stub = _is_stub(existing_result.get('description_plain', ''))
            new_is_stub = _is_stub(result.get('description_plain', ''))

            if existing_is_stub and not new_is_stub:
                # Replace: current winner is a stub; the newcomer is real content
                failed.append(existing_path)
                best[name_lower] = (result, path)
            else:
                # Keep the existing winner (first alphabetically, or both stubs)
                failed.append(path)

    # Second pass: assign sequential IDs and rebuild SQL with correct IDs.
    topics = []
    help_topic_id = start_id
    for result, path in best.values():
        refreshed = process_single_file(path, help_topic_id)
        if refreshed:
            topics.append(refreshed)
            help_topic_id += 1
        else:
            failed.append(path)

    print(f"Processed: {len(topics)} files")
    print(f"Failed: {len(failed)} files")

    return topics, failed


def generate_category_inserts():
    """Generate INSERT statements for the static help_category table."""
    inserts = []
    for cat_id, name, parent_id, url in HELP_CATEGORIES:
        escaped_name = name.replace("'", "''")
        inserts.append(
            f"insert into help_category (help_category_id,name,parent_category_id,url) "
            f"values ({cat_id},'{escaped_name}',{parent_id},'{url}');"
        )
    return inserts


def build_keywords_and_relations(topics):
    """Build help_keyword and help_relation INSERT statements from topics.

    Each word in a topic name becomes a keyword. The help_relation table
    then maps each topic to its keywords, enabling MariaDB's HELP command
    to do keyword-based lookups (e.g. HELP 'SELECT' finds the SELECT topic).

    Duplicate (topic_id, keyword_id) relations are deduplicated so that
    MariaDB's composite primary key constraint is not violated at load time.

    Returns:
        keyword_inserts: list of SQL INSERT statements for help_keyword
        relation_inserts: list of SQL INSERT statements for help_relation
    """
    keyword_to_id = {}
    next_keyword_id = 0
    relations = []
    seen_relations = set()
    
    for topic in topics:
        name = topic['name']
        topic_id = topic['topic_id']
        keywords = extract_keywords(name)
        
        for kw in keywords:
            if kw not in keyword_to_id:
                keyword_to_id[kw] = next_keyword_id
                next_keyword_id += 1
            pair = (topic_id, keyword_to_id[kw])
            if pair not in seen_relations:
                seen_relations.add(pair)
                relations.append(pair)
    
    keyword_inserts = []
    for kw, kid in sorted(keyword_to_id.items(), key=lambda x: x[1]):
        escaped_kw = kw.replace("'", "''")
        keyword_inserts.append(
            f"insert into help_keyword (help_keyword_id,name) values ({kid},'{escaped_kw}');"
        )
    
    relation_inserts = []
    for topic_id, keyword_id in relations:
        relation_inserts.append(
            f"insert into help_relation (help_topic_id,help_keyword_id) values ({topic_id},{keyword_id});"
        )
    
    return keyword_inserts, relation_inserts


def write_output(topics: list, output_file: str = "fill_help_tables.sql"):
    """Write the complete fill_help_tables.sql file.

    Output order matches the original MariaDB file:
      1. GPL preamble + setup statements
      2. help_category INSERTs (static)
      3. help_topic INSERTs (one per doc page)
      4. help_keyword INSERTs (one per unique keyword token)
      5. help_relation INSERTs (topic ↔ keyword mappings)
    """
    category_inserts = generate_category_inserts()
    topic_inserts = [t['sql'] for t in topics]
    keyword_inserts, relation_inserts = build_keywords_and_relations(topics)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(SQL_PREAMBLE)
        f.write('\n')
        for stmt in category_inserts:
            f.write(stmt + '\n')
        f.write('\n')
        for stmt in topic_inserts:
            f.write(stmt + '\n')
        f.write('\n')
        for stmt in keyword_inserts:
            f.write(stmt + '\n')
        f.write('\n')
        for stmt in relation_inserts:
            f.write(stmt + '\n')
    
    print(f"Written to {output_file}")
    print(f"  Categories: {len(category_inserts)}")
    print(f"  Topics: {len(topic_inserts)}")
    print(f"  Keywords: {len(keyword_inserts)}")
    print(f"  Relations: {len(relation_inserts)}")


def main():
    # Discover all eligible Markdown files under server/reference/
    files = get_files(str(REPO_ROOT / "server" / "reference"))
    print(f"Found {len(files)} files to process")
    
    # Extract content and build topic dicts (with deduplication)
    topics, failed = process_batch(files)
    
    # Write fill_help_tables.sql next to this script in help-tables/
    output_file = str(SCRIPT_DIR / "fill_help_tables.sql")
    write_output(topics, output_file)
    
    # Write failed/skipped file list for post-run review
    if failed:
        failed_file = str(SCRIPT_DIR / "failed_files.txt")
        with open(failed_file, 'w') as f:
            for path in failed:
                f.write(path + "\n")
        print(f"Failed files written to {failed_file}")


if __name__ == "__main__":
    main()